# Generated by Django 2.1.3 on 2018-11-28 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('agency_id', models.IntegerField(default=0)),
                ('budget_authority_amount', models.FloatField()),
                ('budget_total', models.FloatField()),
                ('budget_pct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumer_Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumer_references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Federal_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('account_id', models.IntegerField(default=0)),
                ('amount', models.FloatField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federal_accounts', to='cost_compare.Agency')),
            ],
        ),
    ]
