# Generated by Django 2.1.3 on 2018-11-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency_Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_of_total_budget_authority', models.FloatField()),
                ('budget_authority_amount', models.FloatField()),
                ('obligated_amount', models.FloatField()),
                ('active_fq', models.IntegerField(default=0)),
                ('active_fy', models.IntegerField(default=0)),
                ('outlay_amount', models.FloatField()),
                ('abbreviation', models.CharField(max_length=32)),
                ('agency_id', models.IntegerField(default=0)),
                ('agency_name', models.CharField(max_length=128)),
                ('current_total_budget_authority_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Federal_Account_Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account_id', models.IntegerField(default=0)),
                ('account_number', models.CharField(max_length=16)),
                ('code', models.IntegerField(default=0)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
