# Generated by Django 2.1.3 on 2018-11-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_compare', '0002_agency_raw_federal_account_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency_raw',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='active_fq',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='active_fy',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='budget_authority_amount',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='current_total_budget_authority_amount',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='obligated_amount',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='outlay_amount',
        ),
        migrations.RemoveField(
            model_name='agency_raw',
            name='percentage_of_total_budget_authority',
        ),
        migrations.AddField(
            model_name='agency_raw',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agency_raw',
            name='category',
            field=models.CharField(default='agency', max_length=32),
        ),
        migrations.AddField(
            model_name='agency_raw',
            name='code',
            field=models.CharField(default='000', max_length=4),
        ),
        migrations.AddField(
            model_name='agency_raw',
            name='name',
            field=models.CharField(default='no name', max_length=128),
        ),
        migrations.AlterField(
            model_name='agency_raw',
            name='agency_id',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='federal_account_raw',
            name='category',
            field=models.CharField(default='federal_account', max_length=32),
        ),
    ]
