# Generated by Django 2.1.3 on 2018-11-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_compare', '0004_auto_20181129_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Agency_Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgac_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=256)),
                ('toptier_agency_id', models.IntegerField(default=0)),
            ],
        ),
    ]
