# Generated by Django 2.1.3 on 2018-11-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_compare', '0005_list_agency_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_account_id', models.IntegerField(default=0)),
                ('federal_account_name', models.CharField(max_length=256)),
                ('agency_id', models.IntegerField(default=0)),
            ],
        ),
    ]
